# Generated by Django 5.1.6 on 2025-03-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=20)),
                ('picture_link', models.CharField(max_length=70)),
                ('item_name', models.CharField(max_length=40)),
                ('item_description', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'testimonials',
            },
        ),
    ]
