# Generated by Django 5.1.6 on 2025-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_menuitems_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='picture_link',
            field=models.CharField(max_length=200),
        ),
    ]
