# Generated by Django 5.1.6 on 2025-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menuitem_picture_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='picture_link',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
