# Generated by Django 5.1.6 on 2025-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_menuitem_picture_link_menuitem_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeStarTreats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'star treats',
            },
        ),
    ]
