# Generated by Django 5.1.6 on 2025-06-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homestartreats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homeStarTreats',
            new_name='homeStarTreat',
        ),
    ]
