# Generated by Django 5.1.6 on 2025-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_homestartreats_homestartreat'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'member_messages',
            },
        ),
    ]
